name: Deploy CDK to dev stage

# STEP 1: Define the Trigger
on:
  push:
    branches:
      - master

# STEP 2: Define the Machine
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # STEP 3: Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # STEP 4: Runtime
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # STEP 5: Packages
      - name: Install dependencies
        run: npm ci

      # STEP 6: Login
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build the code
        run: npm run build

      # STEP 7: Action
      - name: CDK deploy
        run: npx cdk deploy -c stage=dev --app "npx ts-node infra/bin/infra.ts" --require-approval never

